stages:
  - build
  - test
  - deploy

build:
  script:
    - echo "Building the application..."

test:
  script:
    - echo "Running tests..."

deploy:
  script:
    - echo "Deploying to production..."
